long expr4(long *val);
long expr3(long *val);
long expr2(long *val);
long expr1(long *val);
long Expression(void);
long is_Reg(long op);
long is_r32(long id);
long is_r16(long id);
long is_r8(long id);
long is_rSEG(long id);
long is_rDRG(long id);
long is_rCRG(long id);
long is_rTR(long id);
void fatal_error(char *pst);
void line_error(long num);
void prev_error(char *pst, long line);
char is_ident(char chr);
char isskip(char chr);
void put_hexb(U8 value, FILE *fout);
void put_hexw(U32 value, FILE *fout);
void put_hexd(U32 value, FILE *fout);
U32 get_number(void);
long findrsvd(char *pb, long cb);
long findinst(char *pb, long cb);
long findreg(char *pb, long cb);
long findsymbol(char *pb, long cb);
void DumpGSymbols(void);
void DumpLSymbols(void);
void ReturnToken(void);
long Parse(void);
void Command(void);
long EvalOper1(long op);
long EvalOper(long op);
void ForRef(unsigned char type, long Offset);
void FixUp(unsigned char typef, long Offset, long iSymbol);
void ExtRef(unsigned char EType, long iSymbol);
long GetOper(long op);
void Instruction(void);
void AddMacro(void);
void Storage(void);
void NewSymbol(void);
void Resolve(void);
long readline(void);
void Dispatch(void);
void main(long argc, char *argv[]);
